parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Future\Blog\Post\Controller\:
        resource: '../../src/Post/Controller'
        public: false

    Future\Blog\Post\Repository\:
        resource: '../../src/Post/Repository'
        public: false

    Future\Blog\Post\Form\:
        resource: '../../src/Post/Form'
        public: false

    Future\Blog\Post\Security\:
        resource: '../../src/Post/Security'
        public: false

    Future\Blog\Post\Manager\:
        resource: '../../src/Post/Manager'
        public: false

    Future\Blog\Post\Mapper\:
        resource: '../../src/Post/Mapper'
        public: false

    Future\Blog\Post\Command\:
        resource: '../../src/Post/Command'
        public: false
