framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            export_import: "%env(MESSENGER_TRANSPORT_DSN)%"
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            # async: '%env(MESSENGER_TRANSPORT_DSN)%'
            # failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'

        routing:
            'Future\Blog\User\PostExport\PostExport': export_import
            'Future\Blog\User\PostImport\PostImport': export_import
            # Route your messages to the transports
            # 'App\Message\YourMessage': async
